precompile(Tuple{Type{Base.SystemError}, String, Int32, Nothing})
precompile(Tuple{typeof(Base.display_error), Array{Any, 1}})
precompile(Tuple{typeof(Base.display_error), Base.TTY, Array{Any, 1}})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Base.SystemError, Array{Base.StackTraces.StackFrame, 1}}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Base.SystemError, Array{Base.StackTraces.StackFrame, 1}}, Int64, Int64})
precompile(Tuple{Base.var"#showerror##kw", NamedTuple{(:backtrace,), Tuple{Bool}}, typeof(Base.showerror), Base.IOContext{Base.TTY}, Base.SystemError, Array{Base.StackTraces.StackFrame, 1}})
precompile(Tuple{typeof(Base.show_tuple_as_call), Base.IOContext{Base.TTY}, Symbol, Type, Bool, Base.Iterators.Zip{Tuple{Array{Symbol, 1}, Array{Any, 1}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, Core.TypeofBottom})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, Tuple{}})
