{% set name = "Patchwork" %}
{% set version = "0.1.2" %}

package:
 name: {{ name|lower }}
 version: {{ version }}
	
source: 
 git_url: https://github.com/fethalen/Patchwork.git

build:
 number: 0

requirements:
  build: 
    - {{ compiler('c') }}
    #- julia>=1.0
  host:
  run:

test:
  commmands: 
    - patchwork --help

about:
  home: https://github.com/fethalen/Patchwork
  summary: "Alignment-based exon retrieval and concatenation"

		
