{% set name = "Patchwork" %}
{% set version = "0.1.2" %}

package:
 name: {{ name|lower }}
 version: {{ version }}
	
source: 
 url: https://github.com/fethalen/Patchwork/tree/occupancy/archive
 sha256: 0765a047b7b719f0a7fe520141cbda9e7691e516e05568cdf9e86c271ac3cd69
	
build:
 number: 0

requirements:
  build: 
    - {{ compiler('c') }}
    - julia>=1.0
  host:
  run:

about:
 summary: "Alignment-based exon retrieval and concatenation"

		
