# FROM ubuntu:latest
FROM ubuntu:20.04

RUN apt-get update --fix-missing && apt-get install -y sudo && apt-get install -y apt-utils
RUN sudo apt-get update --fix-missing && sudo apt-get install -y wget gcc --fix-missing

RUN adduser --disabled-password --gecos '' patchwork && adduser patchwork sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER patchwork
WORKDIR /home/patchwork
RUN sudo chmod a+rwx /home/patchwork

# Can we do this without conda? 
RUN wget https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh
RUN bash Anaconda3-2020.11-Linux-x86_64.sh -b
RUN rm Anaconda3-2020.11-Linux-x86_64.sh 

ENV PATH /home/patchwork/anaconda3/bin:$PATH

RUN conda update conda
#RUN conda update anaconda
RUN conda update --all
RUN conda install -c conda-forge julia
RUN conda install -c bioconda diamond

ENV VERSION 0.1.2-pre-alpha6

#RUN git clone https://github.com/fethalen/Patchwork.git && cd Patchwork \
#    && julia src/compile.jl . src/precompiled.jl patchwork
RUN wget https://github.com/fethalen/Patchwork/archive/v$VERSION.tar.gz \
    && tar xvf v$VERSION.tar.gz && cd Patchwork-$VERSION \ 
    && julia -e "import Pkg; Pkg.add([\"ArgParse\",\"PackageCompiler\"]);" \
    && julia src/compile.jl . src/precompiled.jl ../patchwork
RUN ln -s patchwork/bin/patchwork patchwork
ENV PATH patchwork:$PATH

CMD patchwork --help